[package]
name = "memory_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = "0.5.0"
getset = "0.1.2"
crossterm = "0.22.1"
prettytable-rs = "^0.8"
