name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: ["aarch64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "x86_64-unknown-linux-gnu"]
        windows: ["x86_64-pc-windows-gnu"]
    steps:
    - uses: actions/checkout@v2
    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: build for linux
      uses: actions-rs/cargo@v1
      with:
        command: build
        toolchain: stable
        args: --release --bins
    - name: set up linux toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.linux }}
        override: true
    - name: build for linux
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --bins --target ${{ matrix.linux }}
    - name: set up windows toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.windows }}
        override: true
    - name: build for windows
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --bins --target ${{ matrix.linux }}
    
