name: Rust

on:
  release:
     types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
#    - name: test
#      uses: actions-rs/cargo@v1
#      with:
#        command: test
        
  build:
    runs-on: ubuntu-latest
    needs: pre_check
    strategy:
      fail-fast: false
      matrix:
        src: [hrrn, producer_consumer, memory_alloc, bankers_algorithm]
        include:
          - target: "x86_64-pc-windows-gnu"
            archive: "zip"
          - target: "x86_64-unknown-linux-musl"
            archive: "tar.gz tar.xz"
          - target: "x86_64-apple-darwin"
            archive: "zip"
    steps:
    - uses: actions/checkout@v2
    - name: set up linux toolchain
      uses: rust-build/rust-build.action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        RUSTTARGET: ${{ matrix.target }}
        ARCHIVE_TYPES: ${{ matrix.archive }}
        SRC_DIR: ${{ matrix.src }}/
        EXTRA_FILES: "README.md LICENSE"

