name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
        
  build_linux:
    runs-on: ubuntu-latest
    needs: pre_check
    strategy:
      matrix:
        os: ["aarch64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "x86_64-unknown-linux-gnu"]
    steps:
    - name: set up linux toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.linux }}
        override: true
    - name: build for linux
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --bins --target ${{ matrix.os }}
        
  build_windows:
    runs-on: "windows-latest"
    needs: pre_check
    strategy:
      matrix:
        os: ["x86_64-pc-windows-gnu"]
    steps:
    - name: set up windows toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.windows }}
        override: true
    - name: build for windows
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --release --bins --target ${{ matrix.os }}
    
